### ISSUE TITLE
Added templating to MetricsHub configuration to generate the list of resources to monitor dynamically

### ISSUE THREAD

**Issue by bertysentry** [MetricsHub/metricshub-community#438]
## Idea

Use [Velocity](https://velocity.apache.org/) for templating in `metricshub.yaml`.

## Use Case

Generate the list of resources to monitor by MetricsHub dynamically from other sources (files, HTTP, scripts, etc.). Integrate with CMDB, etc.

## How it would work

Configuration file would be `metricshub.yaml.vm` in this scenario. User would write YAML mixed with Velocity templating code. In Velocity, the user can use directives (`#if`, `#foreach`, etc.), variables and objects (`$var`), call object methods (`$obj.myMethod(arg)`). See the [Velocity User Guide](https://velocity.apache.org/engine/2.4/user-guide.html), [Velocity Developer Guide](https://velocity.apache.org/engine/2.4/developer-guide.html), 

User can also call [tools exposed by Velocity](https://velocity.apache.org/tools/3.1/tools-summary.html), as well as our own tools (see how we created the [Sentry Maven Skin Tools](https://github.com/sentrysoftware/maven-skin-tools).

## Example

```yaml
resources:

#set($hostList = $json.fetch("https://my-cmdb/hostList")
#foreach ($host in $hostList.iterator() )
  host:
    attributes:
      host.name: $host.hostname
    protocols:
#if ($host.snmp == "true")
      snmp:
        community: public
#else
      http:
        username: op
        password: op
#end
#end
```

Ideally, we would create our own `$http` Velocity tool, with more capabilities than the simple `fetch()` method of `$json`.
